"""
Pydantic models for API request/response validation.
These models define the shape of data exchanged between client and server.
"""

from pydantic import BaseModel, Field


class AsteroidTarget(BaseModel):
    """
    Complete asteroid mining target profile with orbital mechanics,
    economic valuation, and mission feasibility metrics.
    
    This model is returned by the /api/targets endpoint.
    """
    
    # Identity
    id: str = Field(..., description="JPL Small-Body Database ID")
    full_name: str = Field(..., description="Official asteroid designation")
    
    # Physical Properties
    diameter_km: float = Field(..., description="Estimated diameter in kilometers")
    albedo: float = Field(..., description="Surface reflectivity (0.0-1.0)")
    
    # Orbital Elements (Keplerian)
    inclination: float = Field(..., description="Orbital inclination in degrees")
    moid: float = Field(..., description="Minimum Orbit Intersection Distance (AU)")
    semi_major_axis_au: float = Field(..., description="Semi-major axis in AU")
    eccentricity: float = Field(..., description="Orbital eccentricity (0=circular, 1=parabolic)")
    
    # Classification
    spectral_class: str = Field(..., description="Spectral taxonomy (C, S, or M)")
    pha: bool = Field(..., description="Potentially Hazardous Asteroid flag (JPL designation)")
    
    # Accessibility Metrics
    accessibility_score: float = Field(
        ..., 
        ge=0.0, 
        le=100.0,
        description="Mission accessibility score (0-100). Higher = easier/cheaper to reach."
    )
    
    # Economic Valuation
    estimated_mass_kg: float = Field(..., description="Estimated total mass in kilograms")
    estimated_value_usd: float = Field(
        ..., 
        description="Gross commodity valuation in USD (pre-market-shock)"
    )
    adjusted_value_usd: float = Field(
        ..., 
        description="Market-shock-deflated valuation in USD (accounts for supply flooding)"
    )
    
    # Mission Economics
    mission_cost_usd: float = Field(
        ..., 
        description="Total mission CapEx in USD (launch + delta-v + operations)"
    )
    net_profit_usd: float = Field(
        ..., 
        description="Net profit = adjusted_value_usd - mission_cost_usd (can be negative)"
    )
    
    # ESG Metrics
    earth_co2_offset_tons: float = Field(
        ..., 
        description="CO2 equivalent (tons) avoided vs. terrestrial mining"
    )
    
    # Launch Window
    next_pass_date: str = Field(
        ..., 
        description="Predicted optimal launch window (e.g., 'OCT 2028')"
    )
    
    # Explainable AI
    xai_summary: str = Field(
        ..., 
        description="Plain-English mission briefing generated by XAI engine"
    )
    
    model_config = {
        "json_schema_extra": {
            "example": {
                "id": "2000433",
                "full_name": "433 Eros",
                "diameter_km": 16.84,
                "albedo": 0.25,
                "inclination": 10.83,
                "moid": 0.148,
                "semi_major_axis_au": 1.458,
                "eccentricity": 0.223,
                "spectral_class": "S",
                "pha": False,
                "accessibility_score": 78.34,
                "estimated_mass_kg": 6.69e15,
                "estimated_value_usd": 6.69e16,
                "adjusted_value_usd": 5.12e16,
                "mission_cost_usd": 7.42e9,
                "net_profit_usd": 5.11e16,
                "earth_co2_offset_tons": 2.68e14,
                "next_pass_date": "FEB 2028",
                "xai_summary": "SPECTRAVEIN has classified 433 Eros as an S-Class target..."
            }
        }
    }


class HealthCheckResponse(BaseModel):
    """
    Health check response for monitoring and load balancers.
    """
    status: str = Field(..., description="Service status (Operational, Degraded, Down)")
    service: str = Field(..., description="Service name")
    version: str = Field(..., description="API version")
    environment: str = Field(..., description="Deployment environment")
